[package]
name = "bevy_yscribble_3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
bevy_mod_picking = "0.19.0"
extension-traits = "1.0.1"
smart-default = "0.7.1"
static_assertions = "1.1.0"

[dependencies.yscribble]
path = ".."

[dependencies.yutils]
workspace = true

[lints]
workspace = true

[dev-dependencies]
bevy_editor_pls.workspace = true

[package.metadata.bundle]
identifier = "com.ymap.test-ios690"
resources = ["assets"]
