[package]
name = "bevy_yscribble_3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
bevy_mod_picking = "0.19.0"
extension-traits = "1.0.1"

[dependencies.yscribble]
path = ".."

[dev-dependencies]
bevy_editor_pls.workspace = true
