[package]
name = "bevy_yscribble_3d"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy.workspace = true
bevy_mod_picking = "0.19.0"
bevy_replicon = { version = "0.26.3", optional = true }
document-features = "0.2.8"
extension-traits = "1.0.1"
smart-default = "0.7.1"
static_assertions = "1.1.0"
thiserror = "1.0.61"
tracing = "0.1.40"

[dependencies.yscribble]
path = ".."

[dependencies.yutils]
workspace = true

[features]
default = ["debug"]
## Enables `bevy_mod_picking` debug features without you having to import them yourself
# Enabled by default anynway
debug = ["bevy_mod_picking/debug"]
bevy_replicon = ["dep:bevy_replicon", "bevy_replicon_replicated", "bevy_replicon_parent_sync"]
## Whether to add `ParentSync` components to entities
bevy_replicon_parent_sync = ["dep:bevy_replicon"]
## Whether to add `Replicated` components to entities
bevy_replicon_replicated = ["dep:bevy_replicon"]

[lints]
workspace = true

[dev-dependencies]
bevy_editor_pls.workspace = true

[package.metadata.bundle]
identifier = "com.ymap.test-ios690"
resources = ["assets"]
