[workspace]
members = ["crates/*", "crates/yscribble/bevy_*", "xtask"]
resolver = "2"

[workspace.dependencies.bevy]
version = "0.13.2"
# git = "https://github.com/ActuallyHappening/bevy.git"
# branch = "add-ansi-log-option"

[workspace.dependencies.bevy_editor_pls]
# version = "0.8.1"
git = "https://github.com/ActuallyHappening/bevy_editor_pls.git"
branch = "update-gizmos"

[workspace.dependencies.yutils]
path = "crates/yutils"

[workspace.dependencies.bevy_yscribble_3d]
path = "crates/yscribble/bevy_yscribble_3d"

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.metadata.scripts]
dev-install = "cargo install nu cargo-run-script apple-clis cargo-all-features cargo-bundle"
