[package]
name = "bevy_mobile_example"
version = "0.1.0"
edition = "2021"
description = "test-ios app"
default-run = "bevy_mobile_example"
publish = false

[lib]
crate-type = ["staticlib", "cdylib"]

[workspace]
members = ["xtask"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_cosmic_edit = "0.20.0"
bevy_editor_pls = "0.8.1"
tracing = "0.1.40"

[package.metadata.bundle]
identifier = "com.infimap.InfiMap"
resources = ["assets"]

[package.metadata.scripts]
dev-install = "cargo install nu cargo-run-scripts apple-clis"
open-xcode = "open *.xcodeproj"
