[package]
name = "infi-map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.0"
bevy_editor_pls = "0.8.1"
tracing = "0.1.40"
