[workspace]
members = ["crates/*", "xtask"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.13.2" }

[workspace.metadata.scripts]
dev-install = "cargo install nu cargo-run-script apple-clis cargo-all-features"
open-xcode = "open *.xcodeproj"
