[package]
name = "ysurreal"
version = "0.1.0"
edition = "2021"

[dependencies]
camino = "1.1.7"
clap = { version = "4.5.8", features = ["derive", "env"] }
openssh = { version = "0.10.4", features = ["native-mux", "openssh-mux-client"] }
surrealdb = { workspace = true, features = ["protocol-http"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }

[lints]
workspace = true
