[package]
name = "bevy_ecs_collections"
version = "0.1.0"
edition = "2021"
description = "Helps syncronise collections, e.g. Vec<T>, to entities"

[dependencies]
bevy.workspace = true

[lints]
workspace = true
