[package]
name = "ymap"
version = "0.1.0"
edition = "2021"
description = "test-ios app"
default-run = "ymap"
publish = false

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
bevy_cosmic_edit = { version = "0.20.0", features = ["multicam"] }
bevy_egui = "0.27.1"
derive_more = "0.99.17"
tracing = "0.1.40"

[dependencies.bevy_editor_pls]
# version = "0.8.1"
git = "https://github.com/ActuallyHappening/bevy_editor_pls.git"
branch = "update-gizmos"

[package.metadata.bundle]
identifier = "com.ymap.test-ios69"
resources = ["assets"]
